### ISSUE TITLE
Can you provide trained models?

### ISSUE THREAD

**Issue by daooshee** [Attila94/CIConv#1]
CIConv is really interesting! Thanks a lot for your great work.
I wonder if you can release trained W-* models for the four experiments (Synthetic classification, CODaN classification, Semantic segmentation, Visual place recognition)?

**Comment by Attila94** [comment]
Thanks for your interest!
I will try to release the trained models this week - I'll leave another comment here when I have. Please stay tuned! :)

**Comment by Attila94** [comment]
I've uploaded the weights for experiments 1-3, VPR coming up soon.

**Comment by daooshee** [comment]
Thank you so much!
