### ISSUE TITLE
i have some problems in downloading model.zip.

### ISSUE THREAD

**Issue by Raywoo1** [Attila94/CIConv#11]
In experiment 4, the second downloading link has something wrong.
When i running this commend: wget -cO - https://cloudstor.aarnet.edu.au/plus/s/kya3ZjF5N3WqLVL/download > ./data/models.zip, 
the commend telling me 403：Forbidden.

When i opening that link, the webpage telling me "Access denied. Download of a folder is not allowed."

**Comment by Attila94** [comment]
Hi, thanks for reporting this!
@oravus do you know by any chance if this URL is still active?

**Comment by oravus** [comment]
Hi @Raywoo1, can you please try manually downloading through that link _but without the `download` at the end_, i.e., https://cloudstor.aarnet.edu.au/plus/s/kya3ZjF5N3WqLVL/
[Cloudstor, where the files are stored, is going to be decommissioned; thus they might have disabled folder downloads, we will host data somewhere else, but hope that the reduced link works for you for now.]

**Comment by Raywoo1** [comment]
Dear @Attila94 and @oravus, I appreciate your efforts in providing a solution. However, when attempting to access the cloudstor, a prompt requesting me to select a university to log in appeared. Therefore, I kindly request that you provide me with a new link. Thank you very much for your assistance!

**Comment by oravus** [comment]
@Raywoo1, can you please try the following:
`wget "$(curl -s 'https://universityofadelaide.app.box.com/index.php?folder_id=216398644945&q%5Bshared_item%5D%5Bshared_name%5D=3gu4beadjj3t2iulz63w1jzj6tmc0bve&rm=box_v2_zip_shared_folder' | grep -o '"download_url":"[^"]*' | cut -d':' -f2- | tr -d '"' | cut -c 11- | sed 's/\\\//\//g')" -O models.zip`

**Comment by Raywoo1** [comment]
> @Raywoo1, can you please try the following: `wget "$(curl -s 'https://universityofadelaide.app.box.com/index.php?folder_id=216398644945&q%5Bshared_item%5D%5Bshared_name%5D=3gu4beadjj3t2iulz63w1jzj6tmc0bve&rm=box_v2_zip_shared_folder' | grep -o '"download_url":"[^"]*' | cut -d':' -f2- | tr -d '"' | cut -c 11- | sed 's/\\\//\//g')" -O models.zip`

Thanks, bro. I have tried this link, however, there is an error like http://: Invalid host name.

**Comment by oravus** [comment]
> I have tried this link, however, there is an error like http://: Invalid host name.

that seems to be due to missing `curl`, can you install it: `sudo apt install curl` and then run the full download command I had shared.

**Comment by Raywoo1** [comment]
> > I have tried this link, however, there is an error like http://: Invalid host name.
> 
> that seems to be due to missing `curl`, can you install it: `sudo apt install curl` and then run the full download command I had shared.

I have checked the `curl`. That is ok. The question is like this
![image](https://github.com/Attila94/CIConv/assets/28223203/370c40c9-67ff-457b-8e87-218c53241280)

**Comment by oravus** [comment]
That is strange, I successfully tested the command through two different networks. 
Can you please check if you are able to manually download through [this](https://universityofadelaide.box.com/s/3gu4beadjj3t2iulz63w1jzj6tmc0bve) link (no need to sign up)?

**Comment by Raywoo1** [comment]
> That is strange, I successfully tested the command through two different networks. Can you please check if you are able to manually download through [this](https://universityofadelaide.box.com/s/3gu4beadjj3t2iulz63w1jzj6tmc0bve) link (no need to sign up)?

hhh, this link is working now, thank you so much again!!!

**Comment by oravus** [comment]
Great, but that (long) command is still giving error?

**Comment by Raywoo1** [comment]
> 

yes, and the error is still 'http://: Invalid host name'

**Comment by oravus** [comment]
@Attila94, can you please try that at your end?

**Comment by Attila94** [comment]
> @Attila94, can you please try that at your end?

Works on my end!
