### ISSUE TITLE
HI, i have a little question about the Fig. 6 (Edge map) in the paper

### ISSUE THREAD

**Issue by Raywoo1** [Attila94/CIConv#12]
What a wonderful work!!! And, I am curious about the edge map. How can I get this image, just like the below one in the paper?
![image](https://github.com/Attila94/CIConv/assets/28223203/e842e90d-fab2-4cc5-9ef3-9ced69e050af)

**Comment by Attila94** [comment]
Thanks for your interest! This is the code snippet I used to generate the figures:

````python
import cv2, torchvision

img = 'imgd01.jpg'
inv = 'W'

# load and preprocess input image
i = torchvision.transforms.functional.to_tensor(cv2.imread(img)[:,:,::-1].copy())[None,:,:,:]
# get max value of output
w,_=CIConv2d(inv, k=3, scale=0.)(i)
r = torch.max(torch.abs(w.detach()[0,0,:,:]))
print(r)
w,_=CIConv2d(inv, k=3, scale=-2.5)(i)
r = torch.max(torch.abs(w.detach()[0,0,:,:]))
print(r)

plt.figure(figsize=(20,8))
plt.subplot(1,3,1)
plt.imshow(cv2.imread(img)[:,:,::-1])
plt.subplot(1,3,2)
w,_=CIConv2d(inv, k=3, scale=-0.)(i)
# print(torch.isnan(w).any())
plt.imshow(w.detach()[0,0,:,:], vmin=-r, vmax=r, cmap='bwr')
plt.title('scale=0')
plt.subplot(1,3,3)
w,_=CIConv2d(inv, k=3, scale=-2.5)(i)
# print(torch.isnan(w).any())
plt.imshow(w.detach()[0,0,:,:], vmin=-r, vmax=r, cmap='bwr')
plt.title('scale=-2.5')
_=plt.setp(plt.gcf().get_axes(), xticks=[], yticks=[])
````

**Comment by Raywoo1** [comment]
> Thanks for your interest! This is the code snippet I used to generate the figures:
> 
> ```python
> import cv2, torchvision
> 
> img = 'imgd01.jpg'
> inv = 'W'
> 
> # load and preprocess input image
> i = torchvision.transforms.functional.to_tensor(cv2.imread(img)[:,:,::-1].copy())[None,:,:,:]
> # get max value of output
> w,_=CIConv2d(inv, k=3, scale=0.)(i)
> r = torch.max(torch.abs(w.detach()[0,0,:,:]))
> print(r)
> w,_=CIConv2d(inv, k=3, scale=-2.5)(i)
> r = torch.max(torch.abs(w.detach()[0,0,:,:]))
> print(r)
> 
> plt.figure(figsize=(20,8))
> plt.subplot(1,3,1)
> plt.imshow(cv2.imread(img)[:,:,::-1])
> plt.subplot(1,3,2)
> w,_=CIConv2d(inv, k=3, scale=-0.)(i)
> # print(torch.isnan(w).any())
> plt.imshow(w.detach()[0,0,:,:], vmin=-r, vmax=r, cmap='bwr')
> plt.title('scale=0')
> plt.subplot(1,3,3)
> w,_=CIConv2d(inv, k=3, scale=-2.5)(i)
> # print(torch.isnan(w).any())
> plt.imshow(w.detach()[0,0,:,:], vmin=-r, vmax=r, cmap='bwr')
> plt.title('scale=-2.5')
> _=plt.setp(plt.gcf().get_axes(), xticks=[], yticks=[])
> ```

Oh, thank you so much!!! hhh
