### ISSUE TITLE
Synthetic classification dataset

### ISSUE THREAD

**Issue by eaglezjh** [Attila94/CIConv#2]
Thanks a lot for your great work.
But there are some mistakes here:
FileNotFoundError: [Errno 2] No such file or directory: 'train/02691156.npz'

**Comment by Attila94** [comment]
Thanks for reporting! I'm guessing the error is regarding the Shapenet Illuminants dataset in the synthetic classification experiments?
Have you downloaded & unpacked the dataset as mentioned [here](https://data.4tu.nl/articles/dataset/Shapenet_Illuminants_-_dataset_from_Zero-Shot_Day-Night_Domain_Adaptation_with_a_Physics_Prior_/15141273)?

**Comment by eaglezjh** [comment]
Thank you for your reply. I have downloaded & unpacked the dataset, but I do not see this file in the dataset.

**Comment by Attila94** [comment]
Thanks, can you please post the complete error you're getting?

**Comment by eaglezjh** [comment]
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main(args)
  File "train.py", line 88, in main
    x_train = ShapeNetIlluminants(args.root, split='train', transform=tr_train)
  File "/home/XXX/CIconv/CIConv-main/experiments/1_synthetic_classification/shapenet_illuminants.py", line 87, in __init__
    imsar = np.load(os.path.join(split,c+'.npz'))['arr_0']
  File "/home/XXX/anaconda3/envs/ciconv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'train/02691156.npz'

**Comment by Attila94** [comment]
Should be fixed - .npy files are now generated on the first run. Please let me know if you run into any other issues.
