### ISSUE TITLE
I am getting 0.216 for Dark Zurich .

### ISSUE THREAD

**Issue by hassaanmahmood** [Attila94/CIConv#4]
using python eval.py '/CIConv-main/experiments/3_segmentation/cityscapes_w.pth.tar' --invariant 'W'

Night time driving
Score Average : 0.412
But for DarkZurich
Score Average : 0.216

Although I am getting this warning, but I do not think that can be the issue
/lib/python3.7/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
"Argument interpolation should be of type InterpolationMode instead of int. "
/lib/python3.7/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
"Argument interpolation should be of type InterpolationMode instead of int. "
/lib/python3.7/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
"Argument interpolation should be of type InterpolationMode instead of int. "
/lib/python3.7/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
"Argument interpolation should be of type InterpolationMode instead of int. "

**Comment by Attila94** [comment]
First of all, thanks for your interest!

The reported performance in the paper is on the Dark Zurich test set. In order to evaluate on the test set, you should save your predictions and upload them to the evaluation server: https://competitions.codalab.org/competitions/23553. The warnings are indeed not related to this.

Hope this helps!
