### ISSUE TITLE
dark zurich_test test file

### ISSUE THREAD

**Issue by WANGLEKV** [Attila94/CIConv#7]
hi~ Can you provide the prediction result generation code of Dark Zurich test? The prediction result of my modified code does not meet the official requirements. Thank you so much!

**Comment by WANGLEKV** [comment]
hi~

**Comment by Attila94** [comment]
Hi, sorry for the late reply. Just added the code for generating the Dark Zurich files for online evaluation. Hope this helps!
Cheers,
Attila
