### ISSUE TITLE
Question about the dark zurich_test test file

### ISSUE THREAD

**Issue by stacey-0513** [Attila94/CIConv#8]
Thank you for sharing your great code. But I have some questions about the dark zurich_test test file. Can you provide the prediction result generation code for the Dark Zurich test? My revised code predicts results that do not meet the official requirements. thank you very much!

**Comment by Attila94** [comment]
Hi, sorry for the late reply. Just added the code for generating the Dark Zurich files for online evaluation. Hope this helps!
Cheers,
Attila
